src/Entity/Job.php
<?php

namespace App\Entity;

use App\Repository\JobRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobRepository::class)]
class Job
{
    const SCHEDULED_STATUS = 'scheduled';
    const INVOICEING_STATUS = 'invoicing';
    const TO_PRICE_STATUS = 'to_price';
    const COMPLETED_STATUS = 'completed';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column(length: 1024)]
    private ?string $client_name = null;

    #[ORM\Column(length: 1024)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $contact_number = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getClientName(): ?string
    {
        return $this->client_name;
    }

    public function setClientName(string $client_name): self
    {
        $this->client_name = $client_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getContactNumber(): ?string
    {
        return $this->contact_number;
    }

    public function setContactNumber(string $contact_number): self
    {
        $this->contact_number = $contact_number;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public static function validateStatus(mixed $status) : bool
    {
        return ( $status == Job::COMPLETED_STATUS
            || $status == Job::INVOICEING_STATUS
            || $status == Job::TO_PRICE_STATUS
            || $status == Job::SCHEDULED_STATUS
        );
    }

}

templates/index/index.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Jobs</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<body>
<div style="padding: 30px">

    <div style="width: 80%">
        <h5>Jim Smith's Jobs</h5><form method="get">
            <input type="text"
                   name="search"
                   value="{{ search }}"
                   placeholder="Search..." autofocus></form>
        <table class="table table-border table-striped table-bordered table-hover" >
        <tbody>
        <tr>
            <th>Job ID <a href="/?toggle=id" ><i class="fa fa-fw fa-sort fa-sort-{{ sort.id }}"></i></a></th>
            <th>Contact Name <a href="/?toggle=client_name"><i class="fa fa-fw fa-sort fa-sort-{{ sort.client_name }}"></i></a></th>
            <th>Contact Number <a href="/?toggle=contact_number"><i class="fa fa-fw fa-sort fa-sort-{{ sort.contact_number }}"></i></a></th>
            <th>Address</th>
            <th>Status <a href="/?toggle=status"><i class="fa fa-fw fa-sort fa-sort-{{ sort.status }}"></i></a></th>
        </tr>
        {% for job in jobs %}
            <tr><td  onclick="window.location='/notes/{{ job.id }}';">{{ job.id }}</td>
                <td onclick="window.location='/notes/{{ job.id }}';">{{ job.clientName }}</td>
                <td onclick="window.location='/notes/{{ job.id }}';">{{ job.contactNumber }}</td>
                <td onclick="window.location='/notes/{{ job.id }}';">{{ job.address }}</td>
                <td>
                <select id="statusoptions" onchange="sele(this.value,{{ job.id }});">
                    {% for o in statusoptions %}
                        <option value="{{ o }}"
                                {% if job.status == o %}selected="selected"{% endif %}
                        >{{ o }}</option>
                    {% endfor %}
                </select>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
</div>

<script type="text/javascript" >
    function sele(status, jobId) {
        $.post('/job/status/'+jobId,   // url
            { status: status }, // data to be submit
            function(data, status, jqXHR) {// success callback
                console.log(status);
            });
    }
</script>
</body>
</html>

templates/index/note_edit.html.twig
<html lang="en">
<head>
    <title>Notes</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
    ul {
        columns: 2;
        -webkit-columns: 2;
        -moz-columns: 2;
    }
</style>
</head>
<body>

<div style="width: 60%">
<form action="/note/save" method="post">
    <input type="hidden" name="noteId" value="{{ notes.id }}">
    <input type="hidden" name="jobId" value="{{ notes.jobId }}">
    <div class="form-group">
        <label for="noteText">Note Text</label>
        <textarea name="noteText" class="form-control"  placeholder="Type your note">{{ notes.text }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="button" class="btn" onclick="window.location='/notes/{{ jobId }}'">Cancel</button>
</form>
</div>
</body>
</html>

templates/index/notes.html.twig
<html lang="en">
<head>
    <title>Notes</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body></body>
<a href="/">< back</a>
<div style="padding: 30px">
    <h5>Job Details</h5>
    <ul class="list-group" >
        <li class="list-group-item col-4"><b>JobID:</b> {{ job.id }}</li>
        <li class="list-group-item col-4"><b>Client Name:</b> {{ job.clientName }}</li>
        <li class="list-group-item col-4"><b>Contact Number:</b> {{ job.contactNumber }}</li>
        <li class="list-group-item col-4"><b>Status:</b> {{ job.status }}</li>
        <li class="list-group-item col-4"><b>Created:</b> {{ job.created|date('Y-m-d h:i:sa') }}</li>
    </ul>
    <br>
    <h5>Notes</h5>
    <div style="width: 80%">
    <table class="table table-border table-striped table-bordered table-hover">
        <tr>
            <th>Note ID</th>
            <th>Text</th>
            <th>Created</th>
            <td><a href="/note/edit/{{ job.id }}/0" class="fa-solid fa fa-plus"></a></td>
        </tr>
        {% for note in notes %}
            <tr><td>{{ note.id }}</td>
                <td>
                    {{ note.text }}
                </td>
                <td>{{ note.created|date('Y-m-d h:i:sa') }}</td>
                <td><a href="/note/edit/{{ job.id }}/{{ note.id }}"  class="fa-solid fa-pen"></a></td>
            </tr>
        {% endfor %}

    </table>
    </div>

</div>
</html>